const questionsArray = [
    { question: "/v3.jpg", answers: ["Будет ошибка", "10", "undefined"], correctAnswer: 0},
    { question: "/v1.jpg", answers: ["Answer 1", "Answer 2", "Answer 3"], correctAnswer: 2},
    { question: "Question 3", answers: ["Answer 1", "Answer 2", "Answer 3"], correctAnswer: 0},
    { question: "Question 1", answers: ["Answer 1", "Answer 2", "Answer 3"], correctAnswer: 1},
    { question: "Question 1", answers: ["Answer 1", "Answer 2", "Answer 3"], correctAnswer: 1},
    { question: "Question 1", answers: ["Answer 1", "Answer 2", "Answer 3"], correctAnswer: 0},
    { question: "Question 1", answers: ["Answer 1", "Answer 2", "Answer 3"], correctAnswer: 1},
    { question: "Question 1", answers: ["Answer 1", "Answer 2", "Answer 3"], correctAnswer: 2},
    { question: "Question 1", answers: ["Answer 1", "Answer 2", "Answer 3"], correctAnswer: 0},
    { question: "Question 1", answers: ["Answer 1", "Answer 2", "Answer 3"], correctAnswer: 2},
    { question: "Question 1", answers: ["Answer 1", "Answer 2", "Answer 3"], correctAnswer: 2},
    { question: "Question 1", answers: ["Answer 1", "Answer 2", "Answer 3"], correctAnswer: 0},
    { question: "Question 1", answers: ["Answer 1", "Answer 2", "Answer 3"], correctAnswer: 0},
    { question: "Question 1", answers: ["Answer 1", "Answer 2", "Answer 3"], correctAnswer: 0},
    { question: "Question 1", answers: ["Answer 1", "Answer 2", "Answer 3"], correctAnswer: 0},
    { question: "Question 1", answers: ["Answer 1", "Answer 2", "Answer 3"], correctAnswer: 0},
    { question: "Question 1", answers: ["Answer 1", "Answer 2", "Answer 3"], correctAnswer: 0},
    { question: "Question 1", answers: ["Answer 1", "Answer 2", "Answer 3"], correctAnswer: 0},
    { question: "Question 1", answers: ["Answer 1", "Answer 2", "Answer 3"], correctAnswer: 0},
    { question: "Question 1", answers: ["Answer 1", "Answer 2", "Answer 3"], correctAnswer: 0},
    { question: "Question 1", answers: ["Answer 1", "Answer 2", "Answer 3"], correctAnswer: 0},
    { question: "Question 1", answers: ["Answer 1", "Answer 2", "Answer 3"], correctAnswer: 0},
    { question: "Question 1", answers: ["Answer 1", "Answer 2", "Answer 3"], correctAnswer: 0},
    { question: "Question 1", answers: ["Answer 1", "Answer 2", "Answer 3"], correctAnswer: 0},
    { question: "Question 1", answers: ["Answer 1", "Answer 2", "Answer 3"], correctAnswer: 0},
    { question: "Question 1", answers: ["Answer 1", "Answer 2", "Answer 3"], correctAnswer: 0},
    { question: "Question 1", answers: ["Answer 1", "Answer 2", "Answer 3"], correctAnswer: 0},
    { question: "Question 1", answers: ["Answer 1", "Answer 2", "Answer 3"], correctAnswer: 0},
    { question: "Question 1", answers: ["Answer 1", "Answer 2", "Answer 3"], correctAnswer: 0},
    { question: "Question 1", answers: ["Answer 1", "Answer 2", "Answer 3"], correctAnswer: 0},
    { question: "Question 1", answers: ["Answer 1", "Answer 2", "Answer 3"], correctAnswer: 0},
    { question: "Question 1", answers: ["Answer 1", "Answer 2", "Answer 3"], correctAnswer: 0},
    { question: "Question 1", answers: ["Answer 1", "Answer 2", "Answer 3"], correctAnswer: 0},
    { question: "Question 1", answers: ["Answer 1", "Answer 2", "Answer 3"], correctAnswer: 0},
    { question: "Question 1", answers: ["Answer 1", "Answer 2", "Answer 3"], correctAnswer: 0},
    { question: "Question 1", answers: ["Answer 1", "Answer 2", "Answer 3"], correctAnswer: 0},
    { question: "Question 1", answers: ["Answer 1", "Answer 2", "Answer 3"], correctAnswer: 0},
    { question: "Question 1", answers: ["Answer 1", "Answer 2", "Answer 3"], correctAnswer: 0},
    { question: "Question 1", answers: ["Answer 1", "Answer 2", "Answer 3"], correctAnswer: 0},
    { question: "Question 1", answers: ["Answer 1", "Answer 2", "Answer 3"], correctAnswer: 0},
    { question: "Question 1", answers: ["Answer 1", "Answer 2", "Answer 3"], correctAnswer: 0},
    { question: "Question 1", answers: ["Answer 1", "Answer 2", "Answer 3"], correctAnswer: 0},
    { question: "Question 1", answers: ["Answer 1", "Answer 2", "Answer 3"], correctAnswer: 0},
    { question: "Question 1", answers: ["Answer 1", "Answer 2", "Answer 3"], correctAnswer: 0},
    { question: "Question 1", answers: ["Answer 1", "Answer 2", "Answer 3"], correctAnswer: 0},
    { question: "Question 1", answers: ["Answer 1", "Answer 2", "Answer 3"], correctAnswer: 0},
    { question: "Question 1", answers: ["Answer 1", "Answer 2", "Answer 3"], correctAnswer: 0},
    { question: "Question 1", answers: ["Answer 1", "Answer 2", "Answer 3"], correctAnswer: 0},
    { question: "Question 1", answers: ["Answer 1", "Answer 2", "Answer 3"], correctAnswer: 0},
    { question: "Question 1", answers: ["Answer 1", "Answer 2", "Answer 3"], correctAnswer: 0},
    { question: "Question 1", answers: ["Answer 1", "Answer 2", "Answer 3"], correctAnswer: 0},
    { question: "Question 1", answers: ["Answer 1", "Answer 2", "Answer 3"], correctAnswer: 0},
    { question: "Question 1", answers: ["Answer 1", "Answer 2", "Answer 3"], correctAnswer: 0},
    { question: "Question 1", answers: ["Answer 1", "Answer 2", "Answer 3"], correctAnswer: 0},
    { question: "Question 1", answers: ["Answer 1", "Answer 2", "Answer 3"], correctAnswer: 0},
    { question: "Question 1", answers: ["Answer 1", "Answer 2", "Answer 3"], correctAnswer: 0},
    { question: "Question 1", answers: ["Answer 1", "Answer 2", "Answer 3"], correctAnswer: 0},
    { question: "Question 1", answers: ["Answer 1", "Answer 2", "Answer 3"], correctAnswer: 0},
    { question: "Question 1", answers: ["Answer 1", "Answer 2", "Answer 3"], correctAnswer: 0},
    { question: "Question 1", answers: ["Answer 1", "Answer 2", "Answer 3"], correctAnswer: 0},
    { question: "Question 1", answers: ["Answer 1", "Answer 2", "Answer 3"], correctAnswer: 0},
    { question: "Question 1", answers: ["Answer 1", "Answer 2", "Answer 3"], correctAnswer: 0},
    { question: "Question 1", answers: ["Answer 1", "Answer 2", "Answer 3"], correctAnswer: 0},
    { question: "Question 1", answers: ["Answer 1", "Answer 2", "Answer 3"], correctAnswer: 0},
    { question: "Question 1", answers: ["Answer 1", "Answer 2", "Answer 3"], correctAnswer: 0},
    { question: "Question 1", answers: ["Answer 1", "Answer 2", "Answer 3"], correctAnswer: 0},
    { question: "Question 1", answers: ["Answer 1", "Answer 2", "Answer 3"], correctAnswer: 0},
    { question: "Question 1", answers: ["Answer 1", "Answer 2", "Answer 3"], correctAnswer: 0},
    { question: "Question 1", answers: ["Answer 1", "Answer 2", "Answer 3"], correctAnswer: 0},
    { question: "Question 1", answers: ["Answer 1", "Answer 2", "Answer 3"], correctAnswer: 0},
    { question: "Question 1", answers: ["Answer 1", "Answer 2", "Answer 3"], correctAnswer: 0},
    { question: "Question 1", answers: ["Answer 1", "Answer 2", "Answer 3"], correctAnswer: 0},
    { question: "Question 1", answers: ["Answer 1", "Answer 2", "Answer 3"], correctAnswer: 0},
    { question: "Question 1", answers: ["Answer 1", "Answer 2", "Answer 3"], correctAnswer: 0},
    { question: "Question 1", answers: ["Answer 1", "Answer 2", "Answer 3"], correctAnswer: 0},
    { question: "Question 1", answers: ["Answer 1", "Answer 2", "Answer 3"], correctAnswer: 0},
    { question: "Question 1", answers: ["Answer 1", "Answer 2", "Answer 3"], correctAnswer: 0},
    { question: "Question 1", answers: ["Answer 1", "Answer 2", "Answer 3"], correctAnswer: 0},
    
    { question: "Question 100", answers: ["Answer 1", "Answer 2", "Answer 3"], correctAnswer: 2 }
];

export default questionsArray