const questionsArray = [
  {
    id: 1,
    question: "/q1.png",
    answers: ["Будет ошибка", "10", "undefined"],
    correctAnswer: 2,
  },
  {
    id: 2,
    question: "/q2.png",
    answers: ["0", "1", "2"],
    correctAnswer: 0,
  },
  { 
    id: 3,
    question: "/q3.png",
    answers: ["[3]", "[1, 2, 3]", "[1, 2]"],
    correctAnswer: 2,
  },
  {
    id: 4,
    question: "/q4.png",
    answers: ["2, 4, 3, 1", "1, 2, 3, 4", "2, 3, 4, 1"],
    correctAnswer: 0,
  },
  {
    id: 5,
    question: "/q5.png",
    answers: ["true", "false", "Будет ошибка"],
    correctAnswer: 1,
  },
  {
    id: 6,
    question: "/q6.png",
    answers: ["5", "Будет ошибка", "6"],
    correctAnswer: 1,
  },
  {
    id: 7,
    question: "/q7.png",
    answers: ["10", "'1234'", "'334'"],
    correctAnswer: 2,
  },
  {
    id: 8,
    question: "/q8.png",
    answers: ["[1, 2, 3, 4]", "1, 2, 34", "[1, 2, 3, [4]]"],
    correctAnswer: 1,
  },
  {
    id: 9,
    question: "/q9.png",
    answers: ["  1  ", "  2  ", "  a++  "],
    correctAnswer: 0,
  },
  {
    id: 10,
    question: "/q10.png",
    answers: ["[2, 2, 2]", "NaN", "8"],
    correctAnswer: 2,
  },
  {
    id: 11,
    question: "/q11.png",
    answers: ["1", "undefined", "2"],
    correctAnswer: 2,
  },
  {
    id: 12,
    question: "/q12.png",
    answers: ["6", "3.5", "Будет ошибка"],
    correctAnswer: 0,
  },
  {
    id: 13,
    question: "/q13.png",
    answers: ["7", "   null    ", "5"],
    correctAnswer: 2,
  },
  {
    id: 14,
    question: "/q14.png",
    answers: ["1", "   2   ", "Будет ошибка"],
    correctAnswer: 1,
  },
  {
    id: 15,
    question: "/q15.png",
    answers: ["confirm", "alert", "  prompt  "],
    correctAnswer: 0,
  },
  {
    id: 16,
    question: "/q16.png",
    answers: ["Первый", "Второй", "Оба варианта равнозначны"],
    correctAnswer: 2,
  },
  {
    id: 17,
    question: "/q17.png",
    answers: ["Нет такого оператора", "5", "0"],
    correctAnswer: 2,
  },
  {
    id: 18,
    question: "/q18.png",
    answers: ["2 затем 2", "2 затем 5", "5 затем 5"],
    correctAnswer: 1,
  },
  {
    id: 19,
    question: "/q19.png",
    answers: ["'Неправильно'", "'Правильно'", "undefined"],
    correctAnswer: 0,
  },
  {
    id: 20,
    question: "/q20.png",
    answers: ["2", "Будет ошибка", "3"],
    correctAnswer: 1,
  },
  {
    id: 21,
    question: "/q21.png",
    answers: ["while", "for( ; ; )", "  do while   "],
    correctAnswer: 2,
  },
  {
    id: 22,
    question: "/q22.png",
    answers: ["Привет", "Будет ошибка", "Пока"],
    correctAnswer: 1,
  },
  {
    id: 23,
    question: "/q23.png",
    answers: ["Math.round()", "Math.ceil()", "Math.floor()"],
    correctAnswer: 2,
  },
  {
    id: 24,
    question: "/q24.png",
    answers: ["Pete", "John", " Будет ошибка "],
    correctAnswer: 0,
  },
  {
    id: 25,
    question: "/q25.png",
    answers: ["3", "12", " Будет ошибка "],
    correctAnswer: 0,
  },
  {
    id: 26,
    question: "/q26.png",
    answers: ["'ba+aa", "'baNaNa'", "'baaa'"],
    correctAnswer: 1,
  },
  {
    id: 27,
    question: "/q27.png",
    answers: ["false", "undefined", "true"],
    correctAnswer: 0,
  },
  {
    id: 28,
    question: "/q28.png",
    answers: ["true, true, true", "false, true, false", "true, false, false"],
    correctAnswer: 1,
  },
  {
    id: 29,
    question: "/q29.png",
    answers: ["2", "NaN", " undefined "],
    correctAnswer: 0,
  },
  {
    id: 30,
    question: "/q30.png",
    answers: ["true, true, true", "false, false, true", "true, true, false"],
    correctAnswer: 2,
  },
  {
    id: 31,
    question: "/q31.png ",
    answers: ["true , false", "true, true ", " false, false "],
    correctAnswer: 0,
  },
  {
    id: 32,
    question: "/q32.png ",
    answers: ["3, 2+true, 2true", "3, 21, 2true", "NaN, NaN, NaN"],
    correctAnswer: 1,
  },
  {
    id: 33,
    question: "/q33.png",
    answers: ["  {}, null   ", "{}, {}", "{}, undefined"],
    correctAnswer: 0,
  },
  {
    id: 34,
    question: "/q34.png",
    answers: ["true, false, false", "true, true, false", "false, false, false"],
    correctAnswer: 1,
  },
  {
    id: 35,
    question: "/q35.png",
    answers: ["0, 0, 1", "  NaN, NaN, NaN  ", "NaN, 0, 1"],
    correctAnswer: 0,
  },
  {
    id: 36,
    question: "/q36.png",
    answers: ["3", "undefined", "4"],
    correctAnswer: 1,
  },
  {
    id: 37,
    question: "/q37.png",
    answers: ["false, true", "false, false", " true, false "],
    correctAnswer: 2,
  },
  {
    id: 38,
    question: "/q38.png",
    answers: ["true, false", "false, false", " true, true "],
    correctAnswer: 0,
  },
  {
    id: 39,
    question: "/q39.png",
    answers: ["false, true", "false, false", " true, false "],
    correctAnswer: 2,
  },
  {
    id: 40,
    question: "/q40.png",
    answers: ["'е'", "'П'", "1"],
    correctAnswer: 0,
  },
  {
    id: 41,
    question: "/q41.png",
    answers: ["[ ]", "[ 1, 2 ]", "[ 1, 2, 3 ]"],
    correctAnswer: 0,
  },
  {
    id: 42,
    question: "/q42.png",
    answers: ["[ 1, 2, 3 ]", "[ 1, 3, 2 ]", "[ 1, 3, 2, 3, 3 ]"],
    correctAnswer: 1,
  },
  {
    id: 43,
    question: "/q43.png",
    answers: ["[1, 2, 3 ]", "{ '0': 1, '1': 2, '2': 3 }", "Будет ошибка"],
    correctAnswer: 1,
  },
  {
    id: 44,
    question: "/q44.png",
    answers: ["'Привет!'", "'Hello'", "Будет ошибка"],
    correctAnswer: 0,
  },
  {
    id: 45,
    question: "/q45.png",
    answers: ["  false, true  ", "false, false", " true, false "],
    correctAnswer: 0,
  },
  {
    id: 46,
    question: "/q46.png",
    answers: ["[ 1, 2, ]", " [ 3, 1, 2, 3 ] ", "[ 1, 2, 3, 3 ]"],
    correctAnswer: 1,
  },
  {
    id: 47,
    question: "/q47.png",
    answers: [
      "[ 1, 'a', 'b', 4 ]",
      "[ 1, 2, 'a', 'b', 3, 4 ]",
      "[ 1, 2, 'a', 'b' ]",
    ],
    correctAnswer: 2,
  },
  {
    id: 48,
    question: "/q48.png",
    answers: ["1, false", "1, -1", "   0, 1   "],
    correctAnswer: 2,
  },
  {
    id: 49,
    question: "/q49.png",
    answers: ["true, false, true", "true, true, false", "false, true, false"],
    correctAnswer: 2,
  },
  {
    id: 50,
    question: "/q50.png",
    answers: [
      "[ 'a', 1, 4, 20, 33, ]",
      "[ 1, 20, 33, 4, 'a' ]",
      "[ 1, 4, 20, 33, 'a' ]",
    ],
    correctAnswer: 1,
  },
  {
    id: 51,
    question: "/q51.png",
    answers: [
      "'строка'",
      "[ 'с', 'т', 'р', 'о', 'к', 'а' ]",
      "'с', 'т', 'р', 'о', 'к', 'а'",
    ],
    correctAnswer: 1,
  },
  {
    id: 52,
    question: "/q52.png",
    answers: ["   2   ", "1", "Будет ошибка"],
    correctAnswer: 0,
  },
  {
    id: 53,
    question: "/q53.png",
    answers: ["  false   ", "true", "Так нельзя писать в js"],
    correctAnswer: 0,
  },
  {
    id: 54,
    question: "/q54.png",
    answers: ["3.3333335 и 2.6666665", "3.3 и  2.6", "3 и  2"],
    correctAnswer: 2,
  },
  {
    id: 55,
    question: "/q55.png",
    answers: ["   0   ", "4", "1"],
    correctAnswer: 1,
  },
  {
    id: 56,
    question: "/q56.png",
    answers: ["'name'", "'Петя'", "undefined"],
    correctAnswer: 2,
  },
  {
    id: 57,
    question: "/q57.png",
    answers: ["2, 3 , 1", "  1, 2, 3  ", "3, 2, 1 "],
    correctAnswer: 0,
  },
  {
    id: 58,
    question: "/q58.png",
    answers: ["-4, 0, 4", "-1, 0, 1", "0, 0, 1"],
    correctAnswer: 1,
  },
  {
    id: 59,
    question: "/q59.png",
    answers: [
      "Будет ошибка",
      "['Toyota', 'Saab', 'Volvo', 'Audi']",
      "['Toyota', 'Volvo', 'BMW', 'Audi']",
    ],
    correctAnswer: 2,
  },
  {
    id: 60,
    question: "/q60.png",
    answers: ["выведет от 0 до 4", "выведет от 0 до 5", "выведет от 1 до 5"],
    correctAnswer: 0,
  },
  {
    id: 61,
    question: "/q61.png",
    answers: ["{ 'a', 'b', 1 }", "{ 'a', 'b', '1' }", "{ 'a', 'b', '1', 1 }"],
    correctAnswer: 2,
  },
  {
    id: 62,
    question: "/q62.png",
    answers: ["3", "2", "4"],
    correctAnswer: 0,
  },
  {
    id: 63,
    question: "/q63.png",
    answers: [
      "object, object, number",
      "object, object, object",
      "number, object, number",
    ],
    correctAnswer: 1,
  },
  {
    id: 64,
    question: "/q64.png",
    answers: ["'123'", "123", "'10023'"],
    correctAnswer: 0,
  },
  {
    id: 65,
    question: "/q65.png",
    answers: ["123", "'10023'", "'123'"],
    correctAnswer: 2,
  },
  {
    id: 66,
    question: "/q66.png",
    answers: ["Будет ошибка", "20", "NaN"],
    correctAnswer: 1,
  },
  {
    id: 67,
    question: "/q67.png",
    answers: ["null", "NaN", "'10null'"],
    correctAnswer: 2,
  },
  {
    id: 68,
    question: "/q68.png",
    answers: ["Будет ошибка", "NaN", "Infinity"],
    correctAnswer: 2,
  },
  {
    id: 69,
    question: "/q69.png",
    answers: ["undefined", "[object Window]", "Будет ошибка"],
    correctAnswer: 0,
  },
  {
    id: 70,
    question: "/q70.png",
    answers: ["undefined", "[object Window]", "Будет ошибка"],
    correctAnswer: 1,
  },
  {
    id: 71,
    question: "/q71.png",
    answers: ["{name:'Петя',f:[Function: f]}", "[object Window]", "undefined"],
    correctAnswer: 0,
  },
  {
    id: 72,
    question: "/q72.png",
    answers: ["{name:'Петя',f:[Function: f]}", "[object Window]", "undefined"],
    correctAnswer: 1,
  },
  {
    id: 73,
    question: "/q73.png",
    answers: ["Будет ошибка", "0", "'0'"],
    correctAnswer: 0,
  },
  {
    id: 74,
    question: "/q74.png",
    answers: ["Будет ошибка", "0", "undefined"],
    correctAnswer: 1,
  },
  {
    id: 75,
    question: "/q75.png",
    answers: ["2, 2", "1, 2", "2, 1"],
    correctAnswer: 2,
  },
  {
    id: 76,
    question: "/q76.png",
    answers: ["Будет ошибка", "[1, 2, 3]", "undefined"],
    correctAnswer: 0,
  },
  {
    id: 77,
    question: "/q77.png",
    answers: ["Будет ошибка", "[ 1, 5, 3 ]", "[ 5, 2, 3 ]"],
    correctAnswer: 1,
  },
  {
    id: 78,
    question: "/q78.png",
    answers: ["[3, 3, 3]", "Будет ошибка", "[1, 2, 3]"],
    correctAnswer: 1,
  },

  {
    id: 79,
    question: "/q79.png",
    answers: ["10", "5", "15"],
    correctAnswer: 2,
  },

  {
    id: 80,
    question: "/q80.png",
    answers: ["false", "true", "undefined"],
    correctAnswer: 1,
  },
  {
    id: 81,
    question: "/q81.png",
    answers: ["25", "Нет такого оператора", "2"],
    correctAnswer: 0,
  },
  {
    id: 82,
    question: "/q82.png",
    answers: ["2", "Нет такого оператора", "400"],
    correctAnswer: 2,
  },
  {
    id: 83,
    question: "/q83.png",
    answers: ["4", "105", "5"],
    correctAnswer: 0,
  },
  {
    id: 84,
    question: "/q84.png",
    answers: ["102", "100", "2"],
    correctAnswer: 2,
  },
  {
    id: 85,
    question: "/q85.png",
    answers: ["100", "102", "2"],
    correctAnswer: 1,
  },
  {
    id: 86,
    question: "/q86.png",
    answers: ["undefined", "null", "Будет ошибка"],
    correctAnswer: 0,
  },
  {
    id: 87,
    question: "/q87.png",
    answers: ["6", "10", "15"],
    correctAnswer: 1,
  },
  {
    id: 88,
    question: "/q88.png",
    answers: ["true, true", "true, false", "false, false"],
    correctAnswer: 1,
  },
  {
    id: 89,
    question: "/q89.png",
    answers: ["'a', 10", "10, 10", "5, 10"],
    correctAnswer: 2,
  },
  {
    id: 90,
    question: "/q90.png",
    answers: ["true", "false", "undefined"],
    correctAnswer: 0,
  },
  {
    id: 91,
    question: "/q91.png",
    answers: ["5, 10", "3, 5", "5, 7"],
    correctAnswer: 2,
  },
  {
    id: 92,
    question: "/q92.png",
    answers: ["'Hello!'", "Будет ошибка", "Ничего"],
    correctAnswer: 0,
  },
  {
    id: 93,
    question: "/q93.png",
    answers: ["Петя, Петя", "undefined, Петя", "undefined, undefined"],
    correctAnswer: 0,
  },
  {
    id: 94,
    question: "/q94.png",
    answers: ["Петя, Петя", "undefined, Петя", "undefined, undefined"],
    correctAnswer: 2,
  },
  {
    id: 95,
    question: "/q95.png",
    answers: ["Петя", "Будет ошибка", "undefined"],
    correctAnswer: 1,
  },
  {
    id: 96,
    question: "/q96.png",
    answers: ["27", "Будет ошибка", "undefined"],
    correctAnswer: 0,
  },
  {
    id: 97,
    question: "/q97.png",
    answers: ["true, true", "true, false", "false, false"],
    correctAnswer: 0,
  },
  {
    id: 98,
    question: "/q98.png",
    answers: ["undefined", "'Вася'", "'Петя'"],
    correctAnswer: 2,
  },
  {
    id: 99,
    question: "/q99.png",
    answers: ["false, false", "true, false", "true, true"],
    correctAnswer: 1,
  },
  {
    id: 100,
    question: "/q100.png",
    answers: ["Будет ошибка", "'Hello'", "[Function: foo]"],
    correctAnswer: 1,
  },
];

export default questionsArray;
